# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np



In [29]:
# Create a 1-dimensional NumPy array using np.array()
one_d = np.array([1,2,3,4])

# Create a 2-dimensional NumPy array using np.array()
two_d = np.array([[1,2,3,4],
                  [1,2,3,4]])

# Create a 3-dimensional Numpy array using np.array()

three_d = np.array([[[1,2],
                     [1,2]],
                    
                   [[1,2],
                    [1,2]]])


three_x_three = np.array([[[1,2,3],[1,2,3],[1,2,3]],
                        [[1,2,3],[1,2,3],[1,2,3]],
                        [[1,2,3],[1,2,3],[1,2,3]]])











array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [34]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)

one_d.shape, one_d.size, type(one_d),one_d.dtype, one_d.ndim


((4,), 4, numpy.ndarray, dtype('int64'), 1)

In [36]:
# Attributes of 2-dimensional array
two_d.shape, two_d.size, type(two_d),two_d.dtype, two_d.ndim

((2, 4), 8, numpy.ndarray, dtype('int64'), 2)

In [37]:
# Attributes of 3-dimensional array
three_d.shape, three_d.size, type(three_d),three_d.dtype, three_d.ndim

((2, 2, 2), 8, numpy.ndarray, dtype('int64'), 3)

In [41]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 

df = pd.DataFrame(two_d)
df


0  1  2  3
0  1  2  3  4
1  1  2  3  4

In [44]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [56]:
# Create an array within a range of 0 and 100 with step 3
array = np.arange(0,100,3)
array


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [63]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array = np.random.randint(0,10,size=(7,2))
array


array([[3, 0],
       [1, 2],
       [1, 5],
       [6, 2],
       [4, 6],
       [3, 5],
       [0, 5]])

In [65]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array = np.random.rand(3,5)
array

array([[0.63008758, 0.68926643, 0.78603354, 0.38042968, 0.51669976],
       [0.29449667, 0.58480847, 0.28703512, 0.69832442, 0.76365167],
       [0.44021243, 0.47421167, 0.58579927, 0.94146284, 0.00858453]])

In [69]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array = np.random.randint(0,10, size=(4,6))
array


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [74]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array = np.random.randint(1,10,size=(3,7))
array


# Find the unique numbers in the array you just created
np.unique(array)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [77]:
# Find the 0'th index of the latest array you created
array[0][0],array


(7,
 array([[7, 9, 3, 7, 1, 4, 4],
        [5, 7, 7, 4, 7, 3, 6],
        [2, 9, 5, 6, 4, 7, 9]]))

In [95]:
# Get the first 2 rows of latest array you created
array[:2]



array([[7, 9, 3, 7, 1, 4, 4],
       [5, 7, 7, 4, 7, 3, 6]])

In [96]:
# Get the first 2 values of the first 2 rows of the latest array
array[:2,:2]


array([[7, 9],
       [5, 7]])

In [104]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array = np.random.randint(0,10,size=(3,5))
ones = np.ones((3,5))
array


array([[7, 8, 3, 0, 0],
       [9, 3, 6, 1, 2],
       [0, 4, 0, 7, 0]])

In [103]:
# Add the two arrays together
new = array+ones
new



array([[ 9.,  9.,  4.,  9.,  3.],
       [ 7.,  6.,  8.,  9.,  5.],
       [ 1.,  3., 10.,  8.,  6.]])

In [105]:
# Create another array of ones of shape (5, 3)
ones2 = np.ones((5,3))


In [106]:
# Try add the array of ones and the other most recent array together
ones2+new


ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?


How would you fix it?

In [107]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3,5))


In [108]:
# Subtract the new array of ones from the other most recent array
new-ones


array([[8., 8., 3., 8., 2.],
       [6., 5., 7., 8., 4.],
       [0., 2., 9., 7., 5.]])

In [109]:
# Multiply the ones array with the latest array
ones * new


array([[ 9.,  9.,  4.,  9.,  3.],
       [ 7.,  6.,  8.,  9.,  5.],
       [ 1.,  3., 10.,  8.,  6.]])

In [110]:
# Take the latest array to the power of 2 using '**'
new**2

array([[ 81.,  81.,  16.,  81.,   9.],
       [ 49.,  36.,  64.,  81.,  25.],
       [  1.,   9., 100.,  64.,  36.]])

In [111]:
# Do the same thing with np.square()
np.square(new
         )


array([[ 81.,  81.,  16.,  81.,   9.],
       [ 49.,  36.,  64.,  81.,  25.],
       [  1.,   9., 100.,  64.,  36.]])

In [112]:
# Find the mean of the latest array using np.mean()
new.mean()


6.466666666666667

In [114]:
# Find the maximum of the latest array using np.max()
np.max(new)

10.0

In [115]:
# Find the minimum of the latest array using np.min()
np.min(new)

1.0

In [116]:
# Find the standard deviation of the latest array
np.std(new)

2.6549743668986507

In [118]:
# Find the variance of the latest array
np.var(new)


7.04888888888889

In [124]:
# Reshape the latest array to (3, 5, 1)
new.shape
new.reshape(3,5,1).shape


(3, 5, 1)

In [125]:
# Transpose the latest array
new.T

array([[ 9.,  7.,  1.],
       [ 9.,  6.,  3.],
       [ 4.,  8., 10.],
       [ 9.,  9.,  8.],
       [ 3.,  5.,  6.]])

What does the transpose do?

In [138]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_one = np.random.randint(0,10,size=(3,2))
array_two = np.random.randint(0,10,size=(3,3))
array_one.shape,array_two.shape


((3, 2), (3, 3))

In [140]:
# Perform a dot product on the two newest arrays you created
np.dot(array_one.T,array_two)

array([[54, 93, 69],
       [47, 69, 38]])

In [142]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_one = np.random.randint(0,10,size=(4,3))
array_two = np.random.randint(0,10,size=(4,3))
array_one.shape,array_two.shape


((4, 3), (4, 3))

In [143]:
# Perform a dot product on the two newest arrays you created
np.dot(array_one.T,array_two)


array([[ 65,  47,  60],
       [ 96,  39,  33],
       [148,  70,  18]])

It doesn't work. How would you fix it?

In [145]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

#done above


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [150]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a = np.random.randint(0,10,size=(4,4))
b = np.random.randint(0,10,size=(4,4))





In [151]:
# Compare the two arrays with '>'
a>b


array([[ True, False, False, False],
       [ True, False, False,  True],
       [False, False, False, False],
       [False, False,  True, False]])

What happens when you compare the arrays with `>`?

In [152]:
# Compare the two arrays with '>='
a>=b

array([[ True,  True, False,  True],
       [ True, False, False,  True],
       [False, False, False, False],
       [False, False,  True,  True]])

In [155]:
# Find which elements of the first array are greater than 7
a,a>7


(array([[1, 4, 0, 0],
        [4, 2, 3, 2],
        [0, 0, 4, 5],
        [2, 8, 4, 7]]),
 array([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False,  True, False, False]]))

In [156]:
# Which parts of each array are equal? (try using '==')
a == 7 ,a

(array([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False,  True]]),
 array([[1, 4, 0, 0],
        [4, 2, 3, 2],
        [0, 0, 4, 5],
        [2, 8, 4, 7]]))

In [158]:
# Sort one of the arrays you just created in ascending order
a.sort()
a

array([[0, 0, 1, 4],
       [2, 2, 3, 4],
       [0, 0, 4, 5],
       [2, 4, 7, 8]])

In [159]:
# Sort the indexes of one of the arrays you just created
np.argsort(a)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [162]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a),a

(15,
 array([[0, 0, 1, 4],
        [2, 2, 3, 4],
        [0, 0, 4, 5],
        [2, 4, 7, 8]]))

In [164]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a)


0

In [167]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a,axis=1)


array([3, 3, 3, 3])

In [169]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a,axis=0)


array([0, 0, 0, 0])

In [178]:
# Create an array of normally distributed random numbers
arr_norm = np.random.normal(size=(5,3))



In [180]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr = np.arange(1,100,10)
arr

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.